spring.application.name=tictactoe-global

# Database Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/tictactoe?createDatabaseIfNotExist=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Jlr@2025}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Spring Boot will auto-detect the library dialect, or we can use the generic one
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# WebSocket Configuration (if needed to increase message sizes, etc.)
# server.port=8080
